name: "Experimental Release (Android bundle)"
on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPOSITORY_NAME: ${{ github.event.repository.name }}

permissions:
  write-all

jobs:
  release:
    name: Build and release Android bundle
    runs-on: ubuntu-latest
    steps:
      - name: Generate build variables
        id: vars
        run: |
          timestamp=$(date -u "+%Y-%m-%d-%H%M")
          echo "timestamp=$timestamp" >> $GITHUB_OUTPUT
          echo "tag_name=cdda-experimental-aab-bundle-$timestamp" >> $GITHUB_OUTPUT
          echo "release_name=Cataclysm-DDA experimental Android bundle $timestamp" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gettext

      - name: Build Android bundle
        working-directory: ./android
        run: |
          keytool -genkey -keystore /tmp/a.keystore -keyalg RSA -keysize 2048 -validity 10000 -alias a -dname "cn=a, ou=a, o=a, c=a" -storepass 123456 -keypass 123456
          echo -e "keyPassword=123456\nkeyAlias=a\nstorePassword=123456\nstoreFile=/tmp/a.keystore" > keystore.properties
          export UPSTREAM_BUILD_NUMBER="$((11581 + ${{ github.run_number }}))"
          chmod +x gradlew
          ./gradlew -Pj=$((`nproc`+0)) bundleExperimentalRelease
          mv ./app/build/outputs/bundle/experimentalRelease/*.aab ../cdda-android-bundle-${{ steps.vars.outputs.timestamp }}-${{ github.sha }}.aab
          ls -lh ..
          pwd


      - name: Create GitHub release
        run: |
          ls -lh
          pwd
          gh release create ${{ steps.vars.outputs.tag_name }} \
            cdda-android-bundle-${{ steps.vars.outputs.timestamp }}-${{ github.sha }}.aab \
            --prerelease \
            --title "${{ steps.vars.outputs.release_name }}" \
            --target "${{ github.sha }}"
